name: hire4j

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/hire4j_dev?createDatabaseIfNotExist=true
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
